### ISSUE TITLE
Gregtech ce

### ISSUE THREAD

**Issue by mightydanp** [Coders-After-Dark/CompatSkills#93]
is it possible that you can add gregtechCE support

**Comment by pupnewfster** [comment]
Maybe. If you tell me what things from it would you like to see supported I can look into it. I have not played gregtech since around the tekkit days so I have no idea what is in gregtechCE that could be supported.

**Comment by mightydanp** [comment]
All of gregtech items wouldnt be able to add into being able to be locked because of how there code works. For example a iron pickaxe has the same Id as a flint pickaxe the only difference in the 2 items is the material. Which is how gregtech can have tons of materials and less load times

**Comment by Lanse505** [comment]
Isn't that saved to Nbt though?
If that's the case you can just lock it using NBT

**Comment by pupnewfster** [comment]
I installed Gregtech CE to see how the pickaxes are done, and because of our partial NBT matching, it does not matter that the damage is stored in NBT. So using compatskills you could lock
`<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {PrimaryMaterial: "iridium"}})`
or
`<gregtech:meta_tool:1>.withTag({"GT.ToolStats": {PrimaryMaterial: "osmium"}})`
as the items and it would lock the corresponding pickaxe. You probably could also make a CraftTweaker function that adds the proper NBT tag for a given material for you so then you would lock this as your item `addMaterial(<gregtech:meta_tool:1>, "osmium")` (Note you would have to make an addMaterial method that properly returns an IItemStack with the correct NBT.

**Comment by pupnewfster** [comment]
Is there anything else that gregtech has that you think compat is needed for? Or can I close this as the one example given is already possible to do.

**Comment by mightydanp** [comment]
Would machines work ? There I'd verities have 1-10000. If not I cant think of anything else at the time.

**Comment by pupnewfster** [comment]
I don't believe there would be anything issue with them. If you have any further questions you can always just join our discord. You can also use `/ct hand` while holding the machine to get the IItemStack including the NBT.
